import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/app/_utils/styleUtils'
import { ReactQueryClientProvider } from '@/app/_components/queryProvider'
import { Toaster } from '@/app/_components/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            'container',
            'bg-gradient-to-r from-sky-500 to-indigo-500',
          )}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}
